@echo off 
color a

echo running main.py ....
echo press enter to move forward...
echo btw dont move the main.py files or move any files out the folder...
echo BTW DONT CLOSE THIS WINDOW OR IT WILL CLOSE THE MAIN WINDOW...
pause

python main.py
